### Autenticacao partner 1
# @name loginPartner1
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "partner1@user.com",
    "password": "secret"
}

###
@tokenPartner1 = {{ loginPartner1.response.body.token }}

### Autenticacao partner 2
# @name loginPartner2
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "partner2@user.com",
    "password": "secret"
}

###
@tokenPartner2 = {{ loginPartner2.response.body.token }}

### Autenticacao customer
# @name loginCustomer1
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "customer1@user.com",
    "password": "secret"
}

###
@tokenCustomer1 = {{ loginCustomer1.response.body.token }}

### Criacao do partner 1
POST http://localhost:3000/partners/register
Content-Type: application/json

{
    "name": "partner 1",
    "email": "partner1@user.com",
    "password": "secret",
    "company_name": "company name 1"
}

### Criacao do partner 2
POST http://localhost:3000/partners/register
Content-Type: application/json

{
    "name": "partner 2",
    "email": "partner2@user.com",
    "password": "secret",
    "company_name": "company name 1"
}

### Criacao do customer
POST http://localhost:3000/customers/register
Content-Type: application/json

{
    "name": "customer 1",
    "email": "customer1@user.com",
    "password": "secret",
    "address": "address test",
    "phone": "1639832100"
}

### Criacao do evento pelo parceiros
POST http://localhost:3000/partners/events
Content-Type: application/json
Authorization: Bearer {{ tokenPartner1}}

{
    "name": "event test 1",
    "description": "descricao do evento",
    "date": "2025-11-29T00:00:00",
    "location": "rua x, bairro etc"
}

### Listagem de eventos do parceiro
GET http://localhost:3000/partners/events
Authorization: Bearer {{ tokenPartner1}}

### Listagem de um evento do parceiro
GET http://localhost:3000/partners/events/1
Authorization: Bearer {{ tokenPartner1}}

### Listagem de eventos
GET http://localhost:3000/events

### Listagem de um evento
GET http://localhost:3000/events/1